name: WDIO Automation Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4️⃣ Run tests (ONLY ONCE)
      - name: Execute WebDriverIO Tests
        env:
          MY_APP_URL: ${{ secrets.MY_APP_URL }}
        run: npx wdio run wdio.conf.ts

      # 5️⃣ Upload reports
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            allure-results/
            screenshots/